#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 64
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 7

enum {
  sym_identifier = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_DOT = 6,
  anon_sym_PIPE_PIPE = 7,
  anon_sym_AMP_AMP = 8,
  anon_sym_EQ_EQ = 9,
  anon_sym_BANG_EQ = 10,
  anon_sym_LT = 11,
  anon_sym_GT = 12,
  anon_sym_LT_EQ = 13,
  anon_sym_GT_EQ = 14,
  anon_sym_PLUS = 15,
  anon_sym_DASH = 16,
  anon_sym_STAR = 17,
  anon_sym_SLASH = 18,
  anon_sym_PERCENT = 19,
  anon_sym_BANG = 20,
  anon_sym_var = 21,
  anon_sym_EQ = 22,
  anon_sym_true = 23,
  anon_sym_false = 24,
  sym_num = 25,
  anon_sym_DQUOTE = 26,
  aux_sym_string_token1 = 27,
  sym_comment = 28,
  sym_source_file = 29,
  sym_block = 30,
  sym__expression_block = 31,
  sym__statement_block = 32,
  sym__value = 33,
  sym_argument_list = 34,
  sym_method_call = 35,
  sym__expression = 36,
  sym_logical_or = 37,
  sym_logical_and = 38,
  sym_equality = 39,
  sym_comparison = 40,
  sym_additive = 41,
  sym_multiplicative = 42,
  sym_unary = 43,
  sym__primary = 44,
  sym_assignment = 45,
  sym__statement = 46,
  sym_bool = 47,
  sym_string = 48,
  aux_sym_source_file_repeat1 = 49,
  aux_sym_argument_list_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DOT] = ".",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_BANG] = "!",
  [anon_sym_var] = "var",
  [anon_sym_EQ] = "=",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_num] = "num",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_block] = "block",
  [sym__expression_block] = "_expression_block",
  [sym__statement_block] = "_statement_block",
  [sym__value] = "_value",
  [sym_argument_list] = "argument_list",
  [sym_method_call] = "method_call",
  [sym__expression] = "_expression",
  [sym_logical_or] = "logical_or",
  [sym_logical_and] = "logical_and",
  [sym_equality] = "equality",
  [sym_comparison] = "comparison",
  [sym_additive] = "additive",
  [sym_multiplicative] = "multiplicative",
  [sym_unary] = "unary",
  [sym__primary] = "_primary",
  [sym_assignment] = "assignment",
  [sym__statement] = "_statement",
  [sym_bool] = "bool",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_num] = sym_num,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_block] = sym_block,
  [sym__expression_block] = sym__expression_block,
  [sym__statement_block] = sym__statement_block,
  [sym__value] = sym__value,
  [sym_argument_list] = sym_argument_list,
  [sym_method_call] = sym_method_call,
  [sym__expression] = sym__expression,
  [sym_logical_or] = sym_logical_or,
  [sym_logical_and] = sym_logical_and,
  [sym_equality] = sym_equality,
  [sym_comparison] = sym_comparison,
  [sym_additive] = sym_additive,
  [sym_multiplicative] = sym_multiplicative,
  [sym_unary] = sym_unary,
  [sym__primary] = sym__primary,
  [sym_assignment] = sym_assignment,
  [sym__statement] = sym__statement,
  [sym_bool] = sym_bool,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_num] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__expression_block] = {
    .visible = false,
    .named = true,
  },
  [sym__statement_block] = {
    .visible = false,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_method_call] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_logical_or] = {
    .visible = true,
    .named = true,
  },
  [sym_logical_and] = {
    .visible = true,
    .named = true,
  },
  [sym_equality] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison] = {
    .visible = true,
    .named = true,
  },
  [sym_additive] = {
    .visible = true,
    .named = true,
  },
  [sym_multiplicative] = {
    .visible = true,
    .named = true,
  },
  [sym_unary] = {
    .visible = true,
    .named = true,
  },
  [sym__primary] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_expression = 1,
  field_left = 2,
  field_name = 3,
  field_operand = 4,
  field_receiver = 5,
  field_right = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_expression] = "expression",
  [field_left] = "left",
  [field_name] = "name",
  [field_operand] = "operand",
  [field_receiver] = "receiver",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_expression, 0, .inherited = true},
  [1] =
    {field_operand, 1},
  [2] =
    {field_expression, 1},
  [3] =
    {field_left, 0},
    {field_right, 2},
  [5] =
    {field_name, 1},
    {field_value, 3},
  [7] =
    {field_name, 2},
    {field_receiver, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 22,
  [24] = 24,
  [25] = 24,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 28,
  [30] = 30,
  [31] = 30,
  [32] = 32,
  [33] = 32,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 13,
  [51] = 51,
  [52] = 18,
  [53] = 26,
  [54] = 35,
  [55] = 55,
  [56] = 38,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      if (lookahead == '!') ADVANCE(36);
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '%') ADVANCE(35);
      if (lookahead == '&') ADVANCE(3);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == '*') ADVANCE(33);
      if (lookahead == '+') ADVANCE(31);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '<') ADVANCE(27);
      if (lookahead == '=') ADVANCE(38);
      if (lookahead == '>') ADVANCE(28);
      if (lookahead == '\\') SKIP(13)
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '|') ADVANCE(10);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(7)
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(7)
      if (lookahead == '\r') SKIP(1)
      END_STATE();
    case 3:
      if (lookahead == '&') ADVANCE(24);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(53);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(52);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '=') ADVANCE(37);
      if (lookahead == '\\') SKIP(2)
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(47);
      if (lookahead == '\\') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(51);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 10:
      if (lookahead == '|') ADVANCE(23);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\r') ADVANCE(53);
      if (lookahead == '\r') ADVANCE(54);
      END_STATE();
    case 12:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') SKIP(0)
      END_STATE();
    case 13:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') SKIP(0)
      if (lookahead == '\r') SKIP(12)
      END_STATE();
    case 14:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') SKIP(16)
      END_STATE();
    case 15:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') SKIP(16)
      if (lookahead == '\r') SKIP(14)
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '!') ADVANCE(36);
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '%') ADVANCE(35);
      if (lookahead == '&') ADVANCE(3);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == '*') ADVANCE(33);
      if (lookahead == '+') ADVANCE(31);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '<') ADVANCE(27);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '>') ADVANCE(28);
      if (lookahead == '\\') SKIP(15)
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '|') ADVANCE(10);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(16)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(53);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_num);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead == '\r') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(51);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(51);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '\\') ADVANCE(49);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(6);
      if (lookahead == '*') ADVANCE(45);
      if (lookahead == '/') ADVANCE(51);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(6);
      if (lookahead == '*') ADVANCE(45);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(46);
      if (lookahead == '/') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(51);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(47);
      if (lookahead == '\\') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(51);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != '"') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(50);
      if (lookahead == '"') ADVANCE(53);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(44);
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '\\') ADVANCE(49);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(53);
      if (lookahead == '\\') ADVANCE(11);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == '\\') SKIP(1)
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 't') ADVANCE(3);
      if (lookahead == 'v') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(0)
      if (lookahead == '\r') SKIP(5)
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(0)
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 16},
  [8] = {.lex_state = 16},
  [9] = {.lex_state = 16},
  [10] = {.lex_state = 16},
  [11] = {.lex_state = 16},
  [12] = {.lex_state = 16},
  [13] = {.lex_state = 16},
  [14] = {.lex_state = 16},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 16},
  [19] = {.lex_state = 16},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 16},
  [27] = {.lex_state = 16},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 16},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 16},
  [53] = {.lex_state = 16},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 7},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 8},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_num] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(60),
    [sym_block] = STATE(5),
    [sym__expression_block] = STATE(44),
    [sym__statement_block] = STATE(45),
    [sym__value] = STATE(11),
    [sym_method_call] = STATE(5),
    [sym__expression] = STATE(5),
    [sym_logical_or] = STATE(5),
    [sym_logical_and] = STATE(38),
    [sym_equality] = STATE(35),
    [sym_comparison] = STATE(26),
    [sym_additive] = STATE(18),
    [sym_multiplicative] = STATE(13),
    [sym_unary] = STATE(12),
    [sym__primary] = STATE(11),
    [sym_assignment] = STATE(5),
    [sym__statement] = STATE(5),
    [sym_bool] = STATE(11),
    [sym_string] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_var] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_num] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [sym_block] = STATE(2),
    [sym__expression_block] = STATE(44),
    [sym__statement_block] = STATE(45),
    [sym__value] = STATE(11),
    [sym_method_call] = STATE(2),
    [sym__expression] = STATE(2),
    [sym_logical_or] = STATE(2),
    [sym_logical_and] = STATE(38),
    [sym_equality] = STATE(35),
    [sym_comparison] = STATE(26),
    [sym_additive] = STATE(18),
    [sym_multiplicative] = STATE(13),
    [sym_unary] = STATE(12),
    [sym__primary] = STATE(11),
    [sym_assignment] = STATE(2),
    [sym__statement] = STATE(2),
    [sym_bool] = STATE(11),
    [sym_string] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(28),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(31),
    [anon_sym_DASH] = ACTIONS(34),
    [anon_sym_BANG] = ACTIONS(34),
    [anon_sym_var] = ACTIONS(37),
    [anon_sym_true] = ACTIONS(40),
    [anon_sym_false] = ACTIONS(40),
    [sym_num] = ACTIONS(43),
    [anon_sym_DQUOTE] = ACTIONS(46),
    [sym_comment] = ACTIONS(3),
  },
  [3] = {
    [sym_block] = STATE(4),
    [sym__expression_block] = STATE(44),
    [sym__statement_block] = STATE(45),
    [sym__value] = STATE(11),
    [sym_method_call] = STATE(4),
    [sym__expression] = STATE(51),
    [sym_logical_or] = STATE(51),
    [sym_logical_and] = STATE(38),
    [sym_equality] = STATE(35),
    [sym_comparison] = STATE(26),
    [sym_additive] = STATE(18),
    [sym_multiplicative] = STATE(13),
    [sym_unary] = STATE(12),
    [sym__primary] = STATE(11),
    [sym_assignment] = STATE(4),
    [sym__statement] = STATE(4),
    [sym_bool] = STATE(11),
    [sym_string] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_var] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_num] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [4] = {
    [sym_block] = STATE(2),
    [sym__expression_block] = STATE(44),
    [sym__statement_block] = STATE(45),
    [sym__value] = STATE(11),
    [sym_method_call] = STATE(2),
    [sym__expression] = STATE(2),
    [sym_logical_or] = STATE(2),
    [sym_logical_and] = STATE(38),
    [sym_equality] = STATE(35),
    [sym_comparison] = STATE(26),
    [sym_additive] = STATE(18),
    [sym_multiplicative] = STATE(13),
    [sym_unary] = STATE(12),
    [sym__primary] = STATE(11),
    [sym_assignment] = STATE(2),
    [sym__statement] = STATE(2),
    [sym_bool] = STATE(11),
    [sym_string] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(51),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_var] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_num] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [5] = {
    [sym_block] = STATE(2),
    [sym__expression_block] = STATE(44),
    [sym__statement_block] = STATE(45),
    [sym__value] = STATE(11),
    [sym_method_call] = STATE(2),
    [sym__expression] = STATE(2),
    [sym_logical_or] = STATE(2),
    [sym_logical_and] = STATE(38),
    [sym_equality] = STATE(35),
    [sym_comparison] = STATE(26),
    [sym_additive] = STATE(18),
    [sym_multiplicative] = STATE(13),
    [sym_unary] = STATE(12),
    [sym__primary] = STATE(11),
    [sym_assignment] = STATE(2),
    [sym__statement] = STATE(2),
    [sym_bool] = STATE(11),
    [sym_string] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(53),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_var] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_num] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [6] = {
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym_identifier] = ACTIONS(57),
    [anon_sym_LBRACE] = ACTIONS(55),
    [anon_sym_RBRACE] = ACTIONS(55),
    [anon_sym_LPAREN] = ACTIONS(55),
    [anon_sym_RPAREN] = ACTIONS(55),
    [anon_sym_PIPE_PIPE] = ACTIONS(55),
    [anon_sym_AMP_AMP] = ACTIONS(55),
    [anon_sym_EQ_EQ] = ACTIONS(55),
    [anon_sym_BANG_EQ] = ACTIONS(55),
    [anon_sym_LT] = ACTIONS(57),
    [anon_sym_GT] = ACTIONS(57),
    [anon_sym_LT_EQ] = ACTIONS(55),
    [anon_sym_GT_EQ] = ACTIONS(55),
    [anon_sym_PLUS] = ACTIONS(55),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym_STAR] = ACTIONS(55),
    [anon_sym_SLASH] = ACTIONS(57),
    [anon_sym_PERCENT] = ACTIONS(55),
    [anon_sym_BANG] = ACTIONS(57),
    [anon_sym_var] = ACTIONS(57),
    [anon_sym_true] = ACTIONS(57),
    [anon_sym_false] = ACTIONS(57),
    [sym_num] = ACTIONS(55),
    [anon_sym_DQUOTE] = ACTIONS(55),
    [sym_comment] = ACTIONS(3),
  },
  [7] = {
    [ts_builtin_sym_end] = ACTIONS(59),
    [sym_identifier] = ACTIONS(61),
    [anon_sym_LBRACE] = ACTIONS(59),
    [anon_sym_RBRACE] = ACTIONS(59),
    [anon_sym_LPAREN] = ACTIONS(59),
    [anon_sym_RPAREN] = ACTIONS(59),
    [anon_sym_PIPE_PIPE] = ACTIONS(59),
    [anon_sym_AMP_AMP] = ACTIONS(59),
    [anon_sym_EQ_EQ] = ACTIONS(59),
    [anon_sym_BANG_EQ] = ACTIONS(59),
    [anon_sym_LT] = ACTIONS(61),
    [anon_sym_GT] = ACTIONS(61),
    [anon_sym_LT_EQ] = ACTIONS(59),
    [anon_sym_GT_EQ] = ACTIONS(59),
    [anon_sym_PLUS] = ACTIONS(59),
    [anon_sym_DASH] = ACTIONS(59),
    [anon_sym_STAR] = ACTIONS(59),
    [anon_sym_SLASH] = ACTIONS(61),
    [anon_sym_PERCENT] = ACTIONS(59),
    [anon_sym_BANG] = ACTIONS(61),
    [anon_sym_var] = ACTIONS(61),
    [anon_sym_true] = ACTIONS(61),
    [anon_sym_false] = ACTIONS(61),
    [sym_num] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(59),
    [sym_comment] = ACTIONS(3),
  },
  [8] = {
    [ts_builtin_sym_end] = ACTIONS(63),
    [sym_identifier] = ACTIONS(65),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_RBRACE] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(63),
    [anon_sym_DOT] = ACTIONS(67),
    [anon_sym_PIPE_PIPE] = ACTIONS(63),
    [anon_sym_AMP_AMP] = ACTIONS(63),
    [anon_sym_EQ_EQ] = ACTIONS(63),
    [anon_sym_BANG_EQ] = ACTIONS(63),
    [anon_sym_LT] = ACTIONS(65),
    [anon_sym_GT] = ACTIONS(65),
    [anon_sym_LT_EQ] = ACTIONS(63),
    [anon_sym_GT_EQ] = ACTIONS(63),
    [anon_sym_PLUS] = ACTIONS(63),
    [anon_sym_DASH] = ACTIONS(63),
    [anon_sym_STAR] = ACTIONS(63),
    [anon_sym_SLASH] = ACTIONS(65),
    [anon_sym_PERCENT] = ACTIONS(63),
    [anon_sym_BANG] = ACTIONS(65),
    [anon_sym_var] = ACTIONS(65),
    [anon_sym_true] = ACTIONS(65),
    [anon_sym_false] = ACTIONS(65),
    [sym_num] = ACTIONS(63),
    [anon_sym_DQUOTE] = ACTIONS(63),
    [sym_comment] = ACTIONS(3),
  },
  [9] = {
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_identifier] = ACTIONS(71),
    [anon_sym_LBRACE] = ACTIONS(69),
    [anon_sym_RBRACE] = ACTIONS(69),
    [anon_sym_LPAREN] = ACTIONS(69),
    [anon_sym_RPAREN] = ACTIONS(69),
    [anon_sym_PIPE_PIPE] = ACTIONS(69),
    [anon_sym_AMP_AMP] = ACTIONS(69),
    [anon_sym_EQ_EQ] = ACTIONS(69),
    [anon_sym_BANG_EQ] = ACTIONS(69),
    [anon_sym_LT] = ACTIONS(71),
    [anon_sym_GT] = ACTIONS(71),
    [anon_sym_LT_EQ] = ACTIONS(69),
    [anon_sym_GT_EQ] = ACTIONS(69),
    [anon_sym_PLUS] = ACTIONS(69),
    [anon_sym_DASH] = ACTIONS(69),
    [anon_sym_STAR] = ACTIONS(69),
    [anon_sym_SLASH] = ACTIONS(71),
    [anon_sym_PERCENT] = ACTIONS(69),
    [anon_sym_BANG] = ACTIONS(71),
    [anon_sym_var] = ACTIONS(71),
    [anon_sym_true] = ACTIONS(71),
    [anon_sym_false] = ACTIONS(71),
    [sym_num] = ACTIONS(69),
    [anon_sym_DQUOTE] = ACTIONS(69),
    [sym_comment] = ACTIONS(3),
  },
  [10] = {
    [ts_builtin_sym_end] = ACTIONS(73),
    [sym_identifier] = ACTIONS(75),
    [anon_sym_LBRACE] = ACTIONS(73),
    [anon_sym_RBRACE] = ACTIONS(73),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_RPAREN] = ACTIONS(73),
    [anon_sym_PIPE_PIPE] = ACTIONS(73),
    [anon_sym_AMP_AMP] = ACTIONS(73),
    [anon_sym_EQ_EQ] = ACTIONS(73),
    [anon_sym_BANG_EQ] = ACTIONS(73),
    [anon_sym_LT] = ACTIONS(75),
    [anon_sym_GT] = ACTIONS(75),
    [anon_sym_LT_EQ] = ACTIONS(73),
    [anon_sym_GT_EQ] = ACTIONS(73),
    [anon_sym_PLUS] = ACTIONS(73),
    [anon_sym_DASH] = ACTIONS(73),
    [anon_sym_STAR] = ACTIONS(73),
    [anon_sym_SLASH] = ACTIONS(75),
    [anon_sym_PERCENT] = ACTIONS(73),
    [anon_sym_BANG] = ACTIONS(75),
    [anon_sym_var] = ACTIONS(75),
    [anon_sym_true] = ACTIONS(75),
    [anon_sym_false] = ACTIONS(75),
    [sym_num] = ACTIONS(73),
    [anon_sym_DQUOTE] = ACTIONS(73),
    [sym_comment] = ACTIONS(3),
  },
  [11] = {
    [ts_builtin_sym_end] = ACTIONS(77),
    [sym_identifier] = ACTIONS(79),
    [anon_sym_LBRACE] = ACTIONS(77),
    [anon_sym_RBRACE] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(77),
    [anon_sym_RPAREN] = ACTIONS(77),
    [anon_sym_PIPE_PIPE] = ACTIONS(77),
    [anon_sym_AMP_AMP] = ACTIONS(77),
    [anon_sym_EQ_EQ] = ACTIONS(77),
    [anon_sym_BANG_EQ] = ACTIONS(77),
    [anon_sym_LT] = ACTIONS(79),
    [anon_sym_GT] = ACTIONS(79),
    [anon_sym_LT_EQ] = ACTIONS(77),
    [anon_sym_GT_EQ] = ACTIONS(77),
    [anon_sym_PLUS] = ACTIONS(77),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_STAR] = ACTIONS(77),
    [anon_sym_SLASH] = ACTIONS(79),
    [anon_sym_PERCENT] = ACTIONS(77),
    [anon_sym_BANG] = ACTIONS(79),
    [anon_sym_var] = ACTIONS(79),
    [anon_sym_true] = ACTIONS(79),
    [anon_sym_false] = ACTIONS(79),
    [sym_num] = ACTIONS(77),
    [anon_sym_DQUOTE] = ACTIONS(77),
    [sym_comment] = ACTIONS(3),
  },
  [12] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [sym_identifier] = ACTIONS(83),
    [anon_sym_LBRACE] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(81),
    [anon_sym_RPAREN] = ACTIONS(81),
    [anon_sym_PIPE_PIPE] = ACTIONS(81),
    [anon_sym_AMP_AMP] = ACTIONS(81),
    [anon_sym_EQ_EQ] = ACTIONS(81),
    [anon_sym_BANG_EQ] = ACTIONS(81),
    [anon_sym_LT] = ACTIONS(83),
    [anon_sym_GT] = ACTIONS(83),
    [anon_sym_LT_EQ] = ACTIONS(81),
    [anon_sym_GT_EQ] = ACTIONS(81),
    [anon_sym_PLUS] = ACTIONS(81),
    [anon_sym_DASH] = ACTIONS(81),
    [anon_sym_STAR] = ACTIONS(85),
    [anon_sym_SLASH] = ACTIONS(87),
    [anon_sym_PERCENT] = ACTIONS(85),
    [anon_sym_BANG] = ACTIONS(83),
    [anon_sym_var] = ACTIONS(83),
    [anon_sym_true] = ACTIONS(83),
    [anon_sym_false] = ACTIONS(83),
    [sym_num] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_PLUS,
    ACTIONS(91), 7,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(89), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_DASH,
      sym_num,
      anon_sym_DQUOTE,
  [32] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 7,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(95), 15,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_num,
      anon_sym_DQUOTE,
  [62] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_num,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(101), 1,
      anon_sym_RPAREN,
    STATE(12), 1,
      sym_unary,
    STATE(13), 1,
      sym_multiplicative,
    STATE(18), 1,
      sym_additive,
    STATE(26), 1,
      sym_comparison,
    STATE(35), 1,
      sym_equality,
    STATE(38), 1,
      sym_logical_and,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(16), 3,
      sym__expression,
      sym_logical_or,
      aux_sym_argument_list_repeat1,
    STATE(11), 4,
      sym__value,
      sym__primary,
      sym_bool,
      sym_string,
  [118] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_num,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
    STATE(12), 1,
      sym_unary,
    STATE(13), 1,
      sym_multiplicative,
    STATE(18), 1,
      sym_additive,
    STATE(26), 1,
      sym_comparison,
    STATE(35), 1,
      sym_equality,
    STATE(38), 1,
      sym_logical_and,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 3,
      sym__expression,
      sym_logical_or,
      aux_sym_argument_list_repeat1,
    STATE(11), 4,
      sym__value,
      sym__primary,
      sym_bool,
      sym_string,
  [174] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      sym_identifier,
    ACTIONS(108), 1,
      anon_sym_LPAREN,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    ACTIONS(119), 1,
      sym_num,
    ACTIONS(122), 1,
      anon_sym_DQUOTE,
    STATE(12), 1,
      sym_unary,
    STATE(13), 1,
      sym_multiplicative,
    STATE(18), 1,
      sym_additive,
    STATE(26), 1,
      sym_comparison,
    STATE(35), 1,
      sym_equality,
    STATE(38), 1,
      sym_logical_and,
    ACTIONS(113), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(116), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 3,
      sym__expression,
      sym_logical_or,
      aux_sym_argument_list_repeat1,
    STATE(11), 4,
      sym__value,
      sym__primary,
      sym_bool,
      sym_string,
  [230] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(127), 5,
      anon_sym_BANG,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(125), 12,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_DASH,
      sym_num,
      anon_sym_DQUOTE,
  [263] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 7,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(133), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_DASH,
      sym_num,
      anon_sym_DQUOTE,
  [292] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_num,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(12), 1,
      sym_unary,
    STATE(50), 1,
      sym_multiplicative,
    STATE(52), 1,
      sym_additive,
    STATE(53), 1,
      sym_comparison,
    STATE(54), 1,
      sym_equality,
    STATE(56), 1,
      sym_logical_and,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(58), 2,
      sym__expression,
      sym_logical_or,
    STATE(11), 4,
      sym__value,
      sym__primary,
      sym_bool,
      sym_string,
  [344] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_num,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(12), 1,
      sym_unary,
    STATE(13), 1,
      sym_multiplicative,
    STATE(18), 1,
      sym_additive,
    STATE(26), 1,
      sym_comparison,
    STATE(35), 1,
      sym_equality,
    STATE(38), 1,
      sym_logical_and,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 2,
      sym__expression,
      sym_logical_or,
    STATE(11), 4,
      sym__value,
      sym__primary,
      sym_bool,
      sym_string,
  [396] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_num,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(12), 1,
      sym_unary,
    STATE(40), 1,
      sym_logical_or,
    STATE(50), 1,
      sym_multiplicative,
    STATE(52), 1,
      sym_additive,
    STATE(53), 1,
      sym_comparison,
    STATE(54), 1,
      sym_equality,
    STATE(56), 1,
      sym_logical_and,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 4,
      sym__value,
      sym__primary,
      sym_bool,
      sym_string,
  [447] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_num,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(12), 1,
      sym_unary,
    STATE(13), 1,
      sym_multiplicative,
    STATE(18), 1,
      sym_additive,
    STATE(26), 1,
      sym_comparison,
    STATE(35), 1,
      sym_equality,
    STATE(38), 1,
      sym_logical_and,
    STATE(40), 1,
      sym_logical_or,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 4,
      sym__value,
      sym__primary,
      sym_bool,
      sym_string,
  [498] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_num,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(12), 1,
      sym_unary,
    STATE(37), 1,
      sym_logical_and,
    STATE(50), 1,
      sym_multiplicative,
    STATE(52), 1,
      sym_additive,
    STATE(53), 1,
      sym_comparison,
    STATE(54), 1,
      sym_equality,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 4,
      sym__value,
      sym__primary,
      sym_bool,
      sym_string,
  [546] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_num,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(12), 1,
      sym_unary,
    STATE(13), 1,
      sym_multiplicative,
    STATE(18), 1,
      sym_additive,
    STATE(26), 1,
      sym_comparison,
    STATE(35), 1,
      sym_equality,
    STATE(37), 1,
      sym_logical_and,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 4,
      sym__value,
      sym__primary,
      sym_bool,
      sym_string,
  [594] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(139), 5,
      anon_sym_BANG,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(137), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_DASH,
      sym_num,
      anon_sym_DQUOTE,
  [621] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 5,
      anon_sym_BANG,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(143), 12,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_DASH,
      sym_num,
      anon_sym_DQUOTE,
  [646] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_num,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(12), 1,
      sym_unary,
    STATE(34), 1,
      sym_equality,
    STATE(50), 1,
      sym_multiplicative,
    STATE(52), 1,
      sym_additive,
    STATE(53), 1,
      sym_comparison,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 4,
      sym__value,
      sym__primary,
      sym_bool,
      sym_string,
  [691] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_num,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(12), 1,
      sym_unary,
    STATE(13), 1,
      sym_multiplicative,
    STATE(18), 1,
      sym_additive,
    STATE(26), 1,
      sym_comparison,
    STATE(34), 1,
      sym_equality,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 4,
      sym__value,
      sym__primary,
      sym_bool,
      sym_string,
  [736] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_num,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(12), 1,
      sym_unary,
    STATE(27), 1,
      sym_comparison,
    STATE(50), 1,
      sym_multiplicative,
    STATE(52), 1,
      sym_additive,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 4,
      sym__value,
      sym__primary,
      sym_bool,
      sym_string,
  [778] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_num,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(12), 1,
      sym_unary,
    STATE(13), 1,
      sym_multiplicative,
    STATE(18), 1,
      sym_additive,
    STATE(27), 1,
      sym_comparison,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 4,
      sym__value,
      sym__primary,
      sym_bool,
      sym_string,
  [820] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_num,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(12), 1,
      sym_unary,
    STATE(13), 1,
      sym_multiplicative,
    STATE(19), 1,
      sym_additive,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 4,
      sym__value,
      sym__primary,
      sym_bool,
      sym_string,
  [859] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_num,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(12), 1,
      sym_unary,
    STATE(19), 1,
      sym_additive,
    STATE(50), 1,
      sym_multiplicative,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 4,
      sym__value,
      sym__primary,
      sym_bool,
      sym_string,
  [898] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 4,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(147), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_num,
      anon_sym_DQUOTE,
  [921] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_AMP_AMP,
    ACTIONS(153), 4,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(151), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE_PIPE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_num,
      anon_sym_DQUOTE,
  [946] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_num,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(12), 1,
      sym_unary,
    STATE(14), 1,
      sym_multiplicative,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 4,
      sym__value,
      sym__primary,
      sym_bool,
      sym_string,
  [982] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 4,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(157), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PIPE_PIPE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_num,
      anon_sym_DQUOTE,
  [1004] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(163), 4,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(161), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_num,
      anon_sym_DQUOTE,
  [1028] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_num,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(7), 1,
      sym_unary,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 4,
      sym__value,
      sym__primary,
      sym_bool,
      sym_string,
  [1061] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 4,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(167), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_num,
      anon_sym_DQUOTE,
  [1082] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 4,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(171), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_num,
      anon_sym_DQUOTE,
  [1102] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 4,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(175), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_num,
      anon_sym_DQUOTE,
  [1122] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 4,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(179), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_num,
      anon_sym_DQUOTE,
  [1142] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 4,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(183), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_num,
      anon_sym_DQUOTE,
  [1162] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 4,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(187), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_num,
      anon_sym_DQUOTE,
  [1182] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 4,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(191), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_num,
      anon_sym_DQUOTE,
  [1202] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 4,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(195), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_num,
      anon_sym_DQUOTE,
  [1222] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 4,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(199), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_num,
      anon_sym_DQUOTE,
  [1242] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 4,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(203), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_num,
      anon_sym_DQUOTE,
  [1262] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(207), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(89), 7,
      anon_sym_RPAREN,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1283] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    ACTIONS(209), 4,
      anon_sym_var,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(211), 6,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_num,
      anon_sym_DQUOTE,
  [1304] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(217), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(125), 5,
      anon_sym_RPAREN,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1323] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(137), 3,
      anon_sym_RPAREN,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [1336] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_AMP_AMP,
    ACTIONS(151), 2,
      anon_sym_RPAREN,
      anon_sym_PIPE_PIPE,
  [1347] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_LPAREN,
    STATE(49), 1,
      sym_argument_list,
  [1357] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    ACTIONS(225), 1,
      anon_sym_PIPE_PIPE,
  [1367] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_DQUOTE,
  [1374] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_RPAREN,
  [1381] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_EQ,
  [1388] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      ts_builtin_sym_end,
  [1395] = 2,
    ACTIONS(235), 1,
      aux_sym_string_token1,
    ACTIONS(237), 1,
      sym_comment,
  [1402] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_identifier,
  [1409] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 32,
  [SMALL_STATE(15)] = 62,
  [SMALL_STATE(16)] = 118,
  [SMALL_STATE(17)] = 174,
  [SMALL_STATE(18)] = 230,
  [SMALL_STATE(19)] = 263,
  [SMALL_STATE(20)] = 292,
  [SMALL_STATE(21)] = 344,
  [SMALL_STATE(22)] = 396,
  [SMALL_STATE(23)] = 447,
  [SMALL_STATE(24)] = 498,
  [SMALL_STATE(25)] = 546,
  [SMALL_STATE(26)] = 594,
  [SMALL_STATE(27)] = 621,
  [SMALL_STATE(28)] = 646,
  [SMALL_STATE(29)] = 691,
  [SMALL_STATE(30)] = 736,
  [SMALL_STATE(31)] = 778,
  [SMALL_STATE(32)] = 820,
  [SMALL_STATE(33)] = 859,
  [SMALL_STATE(34)] = 898,
  [SMALL_STATE(35)] = 921,
  [SMALL_STATE(36)] = 946,
  [SMALL_STATE(37)] = 982,
  [SMALL_STATE(38)] = 1004,
  [SMALL_STATE(39)] = 1028,
  [SMALL_STATE(40)] = 1061,
  [SMALL_STATE(41)] = 1082,
  [SMALL_STATE(42)] = 1102,
  [SMALL_STATE(43)] = 1122,
  [SMALL_STATE(44)] = 1142,
  [SMALL_STATE(45)] = 1162,
  [SMALL_STATE(46)] = 1182,
  [SMALL_STATE(47)] = 1202,
  [SMALL_STATE(48)] = 1222,
  [SMALL_STATE(49)] = 1242,
  [SMALL_STATE(50)] = 1262,
  [SMALL_STATE(51)] = 1283,
  [SMALL_STATE(52)] = 1304,
  [SMALL_STATE(53)] = 1323,
  [SMALL_STATE(54)] = 1336,
  [SMALL_STATE(55)] = 1347,
  [SMALL_STATE(56)] = 1357,
  [SMALL_STATE(57)] = 1367,
  [SMALL_STATE(58)] = 1374,
  [SMALL_STATE(59)] = 1381,
  [SMALL_STATE(60)] = 1388,
  [SMALL_STATE(61)] = 1395,
  [SMALL_STATE(62)] = 1402,
  [SMALL_STATE(63)] = 1409,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(8),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(20),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(39),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(62),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(9),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(11),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(61),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary, 3, .production_id = 3),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primary, 3, .production_id = 3),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary, 2, .production_id = 2),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary, 2, .production_id = 2),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary, 1),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primary, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary, 1, .production_id = 1),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary, 1, .production_id = 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplicative, 1),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiplicative, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_additive, 1),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_additive, 1),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplicative, 3, .production_id = 4),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiplicative, 3, .production_id = 4),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [105] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(11),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(20),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(39),
  [116] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(9),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(11),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(61),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 1),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison, 1),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_additive, 3, .production_id = 4),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_additive, 3, .production_id = 4),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equality, 1),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_equality, 1),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 3, .production_id = 4),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison, 3, .production_id = 4),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equality, 3, .production_id = 4),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_equality, 3, .production_id = 4),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_and, 1),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical_and, 1),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_and, 3, .production_id = 4),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical_and, 3, .production_id = 4),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_or, 1),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical_or, 1),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_or, 3, .production_id = 4),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical_or, 3, .production_id = 4),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression_block, 3, .production_id = 3),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression_block, 3, .production_id = 3),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_block, 3),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_block, 3),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 1, .production_id = 1),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 1, .production_id = 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 1),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 1),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_block, 2),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_block, 2),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, .production_id = 5),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4, .production_id = 5),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_call, 4, .production_id = 6),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method_call, 4, .production_id = 6),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [233] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [237] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_COMP0012Language(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
